"""The mansion: rooms, walls, doors, furniture, lamps, patrol routes.

Generated by recursive splits, then furnished. Two invariants the test
holds us to: every room is reachable through doors, and the patrol
schedule is a pure function of time - guard_pos(t) - which is what lets
the ghost solver plan a run through it and the live engine reproduce it.
"""
from __future__ import annotations

import math
import random

from settings import (DOOR_W, FOV_RANGE, G_SPEED_PATROL, LAMP_R,
                      MISSION_SEEDS, WALL, WORLD_H, WORLD_W)

MIN_ROOM = 250.0


class Mansion:
    def __init__(self, mission, attempt=0):
        self.mission = mission
        self.attempt = attempt
        self.seed = MISSION_SEEDS[mission] + attempt * 7919
        rng = random.Random(self.seed)

        self.rooms = []                     # (x, y, w, h) interiors
        self._split(WALL, WALL, WORLD_W - 2 * WALL, WORLD_H - 2 * WALL,
                    rng, 0)
        self.doors = []                     # (x, y, w, h) gaps, for render
        self.walls = self._build_walls(rng)
        self.furniture = self._furnish(rng)
        self.solids = self.walls + [f["rect"] for f in self.furniture]

        self.lamps = self._lamps(rng)       # per room: {pos, lit, switch}
        self._place_goals(rng)
        self.patrols = self._patrols(rng)

    # ------------------------------------------------------------- rooms
    def _split(self, x, y, w, h, rng, depth):
        can_v = w > MIN_ROOM * 2 + WALL
        can_h = h > MIN_ROOM * 2 + WALL
        if depth > 3 or (not can_v and not can_h):
            self.rooms.append((x, y, w, h))
            return
        vertical = can_v and (not can_h or w > h or rng.random() < 0.5)
        if vertical:
            cut = rng.uniform(MIN_ROOM, w - MIN_ROOM - WALL)
            self._split(x, y, cut, h, rng, depth + 1)
            self._split(x + cut + WALL, y, w - cut - WALL, h, rng,
                        depth + 1)
        else:
            cut = rng.uniform(MIN_ROOM, h - MIN_ROOM - WALL)
            self._split(x, y, w, cut, rng, depth + 1)
            self._split(x, y + cut + WALL, w, h - cut - WALL, rng,
                        depth + 1)

    def _build_walls(self, rng):
        walls = [
            (0, 0, WORLD_W, WALL), (0, WORLD_H - WALL, WORLD_W, WALL),
            (0, 0, WALL, WORLD_H), (WORLD_W - WALL, 0, WALL, WORLD_H),
        ]
        self.adj = {i: set() for i in range(len(self.rooms))}
        done = set()
        for i, a in enumerate(self.rooms):
            for j, b in enumerate(self.rooms):
                if j <= i or (i, j) in done:
                    continue
                seg = self._shared_edge(a, b)
                if seg is None:
                    continue
                done.add((i, j))
                vertical, lo, hi, coord = seg
                span = hi - lo
                if span < DOOR_W + 50:
                    # no room for a door: solid wall
                    walls.append(self._edge_rect(vertical, lo, hi, coord))
                    continue
                dpos = rng.uniform(lo + 24, hi - DOOR_W - 24)
                walls.append(self._edge_rect(vertical, lo, dpos, coord))
                walls.append(self._edge_rect(vertical, dpos + DOOR_W, hi,
                                             coord))
                if vertical:
                    self.doors.append({"rect": (coord, dpos, WALL, DOOR_W),
                                       "mid": (coord + WALL / 2,
                                               dpos + DOOR_W / 2),
                                       "rooms": (i, j)})
                else:
                    self.doors.append({"rect": (dpos, coord, DOOR_W, WALL),
                                       "mid": (dpos + DOOR_W / 2,
                                               coord + WALL / 2),
                                       "rooms": (i, j)})
                self.adj[i].add(j)
                self.adj[j].add(i)
        return walls

    @staticmethod
    def _shared_edge(a, b):
        ax, ay, aw, ah = a
        bx, by, bw, bh = b
        if abs((ax + aw + WALL) - bx) < 1:      # b right of a
            lo, hi = max(ay, by), min(ay + ah, by + bh)
            if hi - lo > 40:
                return (True, lo, hi, ax + aw)
        if abs((bx + bw + WALL) - ax) < 1:
            lo, hi = max(ay, by), min(ay + ah, by + bh)
            if hi - lo > 40:
                return (True, lo, hi, bx + bw)
        if abs((ay + ah + WALL) - by) < 1:      # b below a
            lo, hi = max(ax, bx), min(ax + aw, bx + bw)
            if hi - lo > 40:
                return (False, lo, hi, ay + ah)
        if abs((by + bh + WALL) - ay) < 1:
            lo, hi = max(ax, bx), min(ax + aw, bx + bw)
            if hi - lo > 40:
                return (False, lo, hi, by + bh)
        return None

    @staticmethod
    def _edge_rect(vertical, lo, hi, coord):
        if hi <= lo:
            return (coord, lo, WALL, 1)
        if vertical:
            return (coord, lo, WALL, hi - lo)
        return (lo, coord, hi - lo, WALL)

    # --------------------------------------------------------- furnishing
    def _furnish(self, rng):
        furniture = []
        kinds = ("cabinet", "table", "sofa", "crate", "plant")
        for ridx, (x, y, w, h) in enumerate(self.rooms):
            for _ in range(rng.randint(1, 3)):
                kind = rng.choice(kinds)
                fw = rng.uniform(46, 110)
                fh = rng.uniform(30, 60)
                # hug a wall so door lines stay open
                side = rng.randint(0, 3)
                if side == 0:
                    fx, fy = x + rng.uniform(30, max(31, w - fw - 30)), y + 10
                elif side == 1:
                    fx, fy = (x + rng.uniform(30, max(31, w - fw - 30)),
                              y + h - fh - 10)
                elif side == 2:
                    fx, fy = x + 10, y + rng.uniform(30, max(31, h - fh - 30))
                else:
                    fx, fy = (x + w - fw - 10,
                              y + rng.uniform(30, max(31, h - fh - 30)))
                rect = (fx, fy, fw, fh)
                if all(not _overlap(rect, d["rect"], 40)
                       for d in self.doors):
                    furniture.append({"rect": rect, "kind": kind,
                                      "room": ridx,
                                      "v": rng.random()})
        return furniture

    def _lamps(self, rng):
        lit_chance = 0.55 + 0.09 * self.mission
        lamps = []
        for idx, (x, y, w, h) in enumerate(self.rooms):
            door = next((d for d in self.doors if idx in d["rooms"]), None)
            if door is None:
                sx, sy = x + 20, y + 20
            else:
                mx, my = door["mid"]
                sx = min(max(mx + rng.uniform(-60, 60), x + 14),
                         x + w - 14)
                sy = min(max(my + rng.uniform(-60, 60), y + 14),
                         y + h - 14)
            lamps.append({"pos": (x + w / 2, y + h / 2),
                          "lit": rng.random() < lit_chance,
                          "switch": (sx, sy),
                          "relight": 0.0})
        return lamps

    def _place_goals(self, rng):
        # start near the bottom-left room, safe in the farthest room
        order = sorted(range(len(self.rooms)),
                       key=lambda i: (self.rooms[i][1] + self.rooms[i][3],
                                      -self.rooms[i][0]))
        start_room = order[-1]
        sx, sy, sw, sh = self.rooms[start_room]
        self.start = (sx + 40, sy + sh - 40)
        self.exit_pos = (sx + 40, sy + sh - 16)
        far = max(range(len(self.rooms)),
                  key=lambda i: math.hypot(
                      self.rooms[i][0] - sx, self.rooms[i][1] - sy))
        fx, fy, fw, fh = self.rooms[far]
        self.safe_room = far
        self.safe_pos = (fx + fw - 40, fy + 36)
        self.start_room = start_room

    # ------------------------------------------------------------ patrols
    def _patrols(self, rng):
        count = (2, 2, 3, 3, 4)[self.mission]
        patrols = []
        room_ids = list(range(len(self.rooms)))
        for g in range(count):
            # a loop of rooms: random walk out and the same way back
            cur = rng.choice(room_ids)
            if cur == self.start_room and len(room_ids) > 1:
                cur = (cur + 1) % len(room_ids)
            chain = [cur]
            for _ in range(rng.randint(2, 3)):
                nxt = [r for r in self.adj[chain[-1]] if r != chain[-1]]
                if not nxt:
                    break
                chain.append(rng.choice(nxt))
            pts = []
            for a, b in zip(chain, chain[1:]):
                ca = self._room_center(a)
                door = next(d for d in self.doors
                            if set(d["rooms"]) == {a, b})
                pts += [ca, door["mid"]]
            pts.append(self._room_center(chain[-1]))
            loop = pts + pts[-2::-1]            # there and back, closed
            patrols.append({"points": loop,
                            "phase": rng.uniform(0, 1)})
        return patrols

    def _room_center(self, idx):
        x, y, w, h = self.rooms[idx]
        return (x + w / 2, y + h / 2)

    # ------------------------------------------------------------ queries
    def room_at(self, x, y):
        for i, (rx, ry, rw, rh) in enumerate(self.rooms):
            if rx <= x <= rx + rw and ry <= y <= ry + rh:
                return i
        return None

    def is_lit(self, x, y):
        room = self.room_at(x, y)
        if room is None:
            return True
        lamp = self.lamps[room]
        if not lamp["lit"]:
            return False
        lx, ly = lamp["pos"]
        return math.hypot(x - lx, y - ly) < LAMP_R * 1.6

    def solid_circle(self, x, y, r):
        for rx, ry, rw, rh in self.solids:
            nx = max(rx, min(x, rx + rw))
            ny = max(ry, min(y, ry + rh))
            if (x - nx) ** 2 + (y - ny) ** 2 < r * r:
                return True
        return False

    def blocked(self, x1, y1, x2, y2):
        """Line of sight test against walls and tall furniture."""
        for rx, ry, rw, rh in self.solids:
            if _seg_rect(x1, y1, x2, y2, rx, ry, rw, rh):
                return True
        return False

    # ---------------------------------------------- the patrol timetable
    def guard_schedule(self, gidx, t):
        """Pure function of time: (x, y, facing) of guard `gidx` when
        nobody has disturbed him. The solver plans against THIS."""
        pts = self.patrols[gidx]["points"]
        lengths = self.patrols[gidx].get("_len")
        if lengths is None:
            lengths = []
            for a, b in zip(pts, pts[1:]):
                lengths.append(math.hypot(b[0] - a[0], b[1] - a[1]))
            self.patrols[gidx]["_len"] = lengths
            self.patrols[gidx]["_total"] = max(1.0, sum(lengths))
        total = self.patrols[gidx]["_total"]
        dist = (t * G_SPEED_PATROL
                + self.patrols[gidx]["phase"] * total) % total
        for (a, b), seg in zip(zip(pts, pts[1:]), lengths):
            if dist <= seg:
                k = dist / max(1e-9, seg)
                x = a[0] + (b[0] - a[0]) * k
                y = a[1] + (b[1] - a[1]) * k
                facing = math.atan2(b[1] - a[1], b[0] - a[0])
                return x, y, facing
            dist -= seg
        return pts[-1][0], pts[-1][1], 0.0


def _overlap(a, b, pad=0):
    ax, ay, aw, ah = a
    bx, by, bw, bh = b
    return (ax < bx + bw + pad and ax + aw + pad > bx
            and ay < by + bh + pad and ay + ah + pad > by)


def _seg_rect(x1, y1, x2, y2, rx, ry, rw, rh):
    """Segment vs axis-aligned rect (slab method)."""
    dx, dy = x2 - x1, y2 - y1
    tmin, tmax = 0.0, 1.0
    for lo, hi, o, d in ((rx, rx + rw, x1, dx), (ry, ry + rh, y1, dy)):
        if abs(d) < 1e-9:
            if o < lo or o > hi:
                return False
        else:
            t1, t2 = (lo - o) / d, (hi - o) / d
            if t1 > t2:
                t1, t2 = t2, t1
            tmin, tmax = max(tmin, t1), min(tmax, t2)
            if tmin > tmax:
                return False
    return True
